import numpy as np 
import pandas as pd 
##########################################################################################
##This script aim to generate the amount generated by the portfolio during the past year##
##Regarding to the distribution of each asset in the portfolio                          ##
##########################################################################################


def Distribution_Portfolio(Amount_Each_Value,df_open,df_high,df_low,df_close) :
    #If there is a uniform repartition
    if isinstance(Amount_Each_Value, (int, float)) : 

        def Quantity(Asset_Price,Amount_Each_Value) : 
            Asset_Price = np.round(Asset_Price, 5)
            return int(Amount_Each_Value/Asset_Price)

        DataFrame_Distribution = []
        for i in range(0,len(df_close.iloc[0])): 
            DataFrame_Distribution.append(Quantity(df_close.iloc[0][i],Amount_Each_Value))

        if isinstance(df_open,pd.DataFrame) : 
            Value_Portfolio_Open = []
            Value_Portfolio_High = []
            Value_Portfolio_Low = []
        
        Value_Portfolio_Close = []

        for i in range(0,len(df_close)) : 
            if isinstance(df_open,pd.DataFrame) : 
                Value_Open = df_open.iloc[i]*DataFrame_Distribution
                Value_High = df_high.iloc[i]*DataFrame_Distribution
                Value_Low = df_low.iloc[i]*DataFrame_Distribution
                
                Value_Portfolio_Open.append(np.sum(Value_Open))
                Value_Portfolio_High.append(np.sum(Value_High))
                Value_Portfolio_Low.append(np.sum(Value_Low))
            
            Value_Close = df_close.iloc[i]*DataFrame_Distribution
            Value_Portfolio_Close.append(np.sum(Value_Close))


        if isinstance(df_open,pd.DataFrame) : 
            df_open_bis = df_open.copy()
            df_open_bis["Portfolio"] = Value_Portfolio_Open
            df_portfolio_open = df_open_bis[["Portfolio"]]
        
            df_high_bis = df_high.copy()
            df_high_bis["Portfolio"] = Value_Portfolio_Open
            df_portfolio_high = df_high_bis[["Portfolio"]]
        
            df_low_bis = df_low.copy()
            df_low_bis["Portfolio"] = Value_Portfolio_Low
            df_portfolio_low = df_low_bis[["Portfolio"]]
        
        df_close_bis = df_close.copy()
        df_close_bis["Portfolio"] = Value_Portfolio_Close
        df_portfolio_close = df_close_bis[["Portfolio"]]


        if isinstance(df_open,pd.DataFrame) :
            return df_portfolio_open, df_portfolio_high, df_portfolio_low, df_portfolio_close, DataFrame_Distribution
        else : 
            return df_portfolio_close, DataFrame_Distribution

    #If there is a non-uniform distribution
    elif isinstance(Amount_Each_Value, (list,tuple)) : 

        def Quantity(Asset_Price,Amount_Each_Value) : 
            Asset_Price = np.round(Asset_Price, 5)
            if Amount_Each_Value!=0: 
                return int(Amount_Each_Value/Asset_Price)
            else : 
                return 0


        DataFrame_Distribution = []
        for i in range(0,len(df_close.iloc[0])): 
            DataFrame_Distribution.append(Quantity(df_close.iloc[0][i],Amount_Each_Value[i]))



        if isinstance(df_open,pd.DataFrame) :
            Value_Portfolio_Open = []
            Value_Portfolio_High = []
            Value_Portfolio_Low = []
        
        Value_Portfolio_Close = []

        for i in range(0,len(df_close)) : 
            if isinstance(df_open,pd.DataFrame) : 
                Value_Open = df_open.iloc[i]*DataFrame_Distribution
                Value_High = df_high.iloc[i]*DataFrame_Distribution
                Value_Low = df_low.iloc[i]*DataFrame_Distribution
                Value_Portfolio_Open.append(np.sum(Value_Open))
                Value_Portfolio_High.append(np.sum(Value_High))
                Value_Portfolio_Low.append(np.sum(Value_Low))
            
            Value_Close = df_close.iloc[i]*DataFrame_Distribution
            Value_Portfolio_Close.append(np.sum(Value_Close))




        if isinstance(df_open,pd.DataFrame) : 
            df_open_bis = df_open.copy()
            df_open_bis["Portfolio"] = Value_Portfolio_Open
            df_portfolio_open = df_open_bis[["Portfolio"]]
        
            df_high_bis = df_high.copy()
            df_high_bis["Portfolio"] = Value_Portfolio_Open
            df_portfolio_high = df_high_bis[["Portfolio"]]
        
            df_low_bis = df_low.copy()
            df_low_bis["Portfolio"] = Value_Portfolio_Low
            df_portfolio_low = df_low_bis[["Portfolio"]]
        
        df_close_bis = df_close.copy()
        df_close_bis["Portfolio"] = Value_Portfolio_Close
        df_portfolio_close = df_close_bis[["Portfolio"]]


        if isinstance(df_open,pd.DataFrame) :
            return df_portfolio_open, df_portfolio_high, df_portfolio_low, df_portfolio_close, DataFrame_Distribution
        else : 
            return df_portfolio_close, DataFrame_Distribution